#!/usr/bin/env python

import argparse
import os.path

import prototurk
import prototurk.version


def main():
    parser = argparse.ArgumentParser(
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument('--port', default=8080)
    parser.add_argument('--host', default='localhost')
    parser.add_argument('--js-map-path', default='',
                        help='Path to directory containing .js.map files')
    parser.add_argument('--version', action='version', version=prototurk.version.__version__)
    parser.add_argument('html_file')
    parser.add_argument('csv_file')
    args = parser.parse_args()

    ms = prototurk.ProtoTurkServer(
        args.host,
        args.port,
        os.path.realpath(args.html_file),
        os.path.realpath(args.csv_file),
        os.path.realpath(args.js_map_path))
    ms.serve()


if __name__ == '__main__':
    main()
